// <auto-generated />
using System;
using System.Net;
using KuraStorage.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KuraStorage.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KuraStorageDbContext))]
    [Migration("20260723131233_AddFileOperations")]
    partial class AddFileOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KuraStorage.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_device_id");

                    b.Property<string>("ActorOsUser")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor_os_user");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_id");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("result_code");

                    b.Property<string>("TargetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ActorUserId", "CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Files.FileEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("entry_type");

                    b.Property<long>("FileVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("file_version");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OriginalParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_parent_id");

                    b.Property<string>("OriginalRelativePath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("original_relative_path");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("relative_path");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TrashedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trashed_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_file_entries_active_owner_root")
                        .HasFilter("\"parent_id\" IS NULL AND \"status\" = 'ACTIVE'");

                    b.HasIndex("ParentId");

                    b.HasIndex("OwnerUserId", "RelativePath")
                        .IsUnique()
                        .HasDatabaseName("ux_file_entries_trashed_owner_path")
                        .HasFilter("\"status\" = 'TRASHED'");

                    b.HasIndex("OwnerUserId", "ParentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_file_entries_active_owner_parent_name")
                        .HasFilter("\"status\" = 'ACTIVE'");

                    b.HasIndex("OwnerUserId", "ParentId", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_file_entries_owner_parent_status_updated_at");

                    b.ToTable("file_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_file_entries_file_version_positive", "\"file_version\" >= 1");

                            t.HasCheckConstraint("ck_file_entries_size_nonnegative", "\"size\" >= 0");
                        });
                });

            modelBuilder.Entity("KuraStorage.Domain.Files.FileOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ExpectedSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("expected_sha256");

                    b.Property<long?>("ExpectedSize")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_size");

                    b.Property<Guid?>("FileEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_entry_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operation_type");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("SourceRelativePath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_relative_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TargetRelativePath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("target_relative_path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FileEntryId")
                        .HasDatabaseName("ix_file_operations_file_entry_id");

                    b.HasIndex("OwnerUserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_file_operations_owner_idempotency_key")
                        .HasFilter("\"idempotency_key\" IS NOT NULL");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_file_operations_status_updated_at");

                    b.ToTable("file_operations", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Identity.AuthenticationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<IPAddress>("RemoteAddress")
                        .HasColumnType("inet")
                        .HasColumnName("remote_address");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("result_code");

                    b.Property<byte[]>("UsernameHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("username_hash");

                    b.HasKey("Id");

                    b.HasIndex("UsernameHash", "CreatedAt");

                    b.ToTable("authentication_attempts", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Identity.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Identity.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasFilter("revoked_at IS NULL AND used_at IS NULL AND replaced_by_session_id IS NULL");

                    b.HasIndex("FamilyId");

                    b.HasIndex("ReplacedBySessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_sessions", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<DateTimeOffset?>("FailedLoginWindowStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_login_window_started_at");

                    b.Property<string>("LockType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("lock_type");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username_normalized");

                    b.HasKey("Id");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Files.FileEntry", b =>
                {
                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KuraStorage.Domain.Files.FileEntry", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KuraStorage.Domain.Files.FileOperation", b =>
                {
                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Identity.Device", b =>
                {
                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Identity.RefreshSession", b =>
                {
                    b.HasOne("KuraStorage.Domain.Identity.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuraStorage.Domain.Identity.RefreshSession", null)
                        .WithMany()
                        .HasForeignKey("ReplacedBySessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
