// <auto-generated />
using System;
using System.Net;
using KuraStorage.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KuraStorage.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KuraStorageDbContext))]
    [Migration("20260829054814_AddMediaDerivativeFoundation")]
    partial class AddMediaDerivativeFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KuraStorage.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_device_id");

                    b.Property<string>("ActorOsUser")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor_os_user");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("SYSTEM")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_id");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("result_code");

                    b.Property<string>("TargetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ActorUserId", "CreatedAt");

                    b.HasIndex("Action", "TargetId", "ResultCode")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_logs_purge_success")
                        .HasFilter("\"action\" IN ('FILE_PURGE_MANUAL', 'FILE_PURGE_RETENTION') AND \"result_code\" = 'SUCCESS'");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Files.FileEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("entry_type");

                    b.Property<long>("FileVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("file_version");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime_type");

                    b.Property<DateTimeOffset?>("MissingDetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("missing_detected_at");

                    b.Property<DateTimeOffset?>("MissingLastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("missing_last_checked_at");

                    b.Property<Guid?>("MissingObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("missing_observation_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OriginalParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_parent_id");

                    b.Property<string>("OriginalRelativePath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("original_relative_path");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("relative_path");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("SourceFileKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_file_key");

                    b.Property<DateTimeOffset?>("SourceModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_modified_at");

                    b.Property<DateTimeOffset?>("SourceObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_observed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TrashedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trashed_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_file_entries_active_owner_root")
                        .HasFilter("\"parent_id\" IS NULL AND \"status\" = 'ACTIVE'");

                    b.HasIndex("ParentId");

                    b.HasIndex("OwnerUserId", "RelativePath")
                        .IsUnique()
                        .HasDatabaseName("ux_file_entries_trashed_owner_path")
                        .HasFilter("\"status\" = 'TRASHED'");

                    b.HasIndex("OwnerUserId", "ParentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_file_entries_managed_owner_parent_name")
                        .HasFilter("\"status\" IN ('ACTIVE', 'MISSING_CANDIDATE', 'MISSING')");

                    b.HasIndex("Status", "MissingLastCheckedAt", "Id")
                        .HasDatabaseName("ix_file_entries_missing_status_checked_at")
                        .HasFilter("\"status\" IN ('MISSING_CANDIDATE', 'MISSING')");

                    b.HasIndex("OwnerUserId", "ParentId", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_file_entries_owner_parent_status_updated_at");

                    b.HasIndex("Status", "ParentId", "TrashedAt", "Id")
                        .HasDatabaseName("ix_file_entries_trash_purge_candidates");

                    b.HasIndex(new[] { "OwnerUserId", "RelativePath" }, "IX_FileEntries_ManagedOwnerPath")
                        .IsUnique()
                        .HasDatabaseName("ux_file_entries_managed_owner_path")
                        .HasFilter("\"status\" IN ('ACTIVE', 'MISSING_CANDIDATE', 'MISSING')");

                    b.ToTable("file_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_file_entries_file_version_positive", "\"file_version\" >= 1");

                            t.HasCheckConstraint("ck_file_entries_missing_metadata", "(\"status\" IN ('ACTIVE', 'TRASHED') AND \"missing_detected_at\" IS NULL AND \"missing_last_checked_at\" IS NULL AND \"missing_observation_id\" IS NULL) OR (\"status\" IN ('MISSING_CANDIDATE', 'MISSING') AND \"parent_id\" IS NOT NULL AND \"missing_detected_at\" IS NOT NULL AND \"missing_last_checked_at\" IS NOT NULL AND \"missing_observation_id\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_file_entries_size_nonnegative", "\"size\" >= 0");
                        });
                });

            modelBuilder.Entity("KuraStorage.Domain.Files.FileOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_device_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ExpectedSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("expected_sha256");

                    b.Property<long?>("ExpectedSize")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_size");

                    b.Property<Guid?>("FileEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_entry_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("operation_type");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_id");

                    b.Property<string>("SourceRelativePath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_relative_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TargetRelativePath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("target_relative_path");

                    b.Property<string>("Trigger")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FileEntryId")
                        .IsUnique()
                        .HasDatabaseName("ux_file_operations_incomplete_purge_target")
                        .HasFilter("\"operation_type\" = 'PURGE' AND \"status\" IN ('PENDING', 'FILESYSTEM_DONE', 'RECOVERY_REQUIRED')");

                    b.HasIndex("OwnerUserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_file_operations_owner_idempotency_key")
                        .HasFilter("\"idempotency_key\" IS NOT NULL");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_file_operations_status_updated_at");

                    b.ToTable("file_operations", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Files.RecentFile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.HasKey("UserId", "FileId");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_recent_files_file_id");

                    b.HasIndex("UserId", "OpenedAt", "FileId")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_recent_files_user_opened_at_file_id");

                    b.ToTable("recent_files", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Identity.AuthenticationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<IPAddress>("RemoteAddress")
                        .HasColumnType("inet")
                        .HasColumnName("remote_address");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("result_code");

                    b.Property<byte[]>("UsernameHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("username_hash");

                    b.HasKey("Id");

                    b.HasIndex("UsernameHash", "CreatedAt");

                    b.ToTable("authentication_attempts", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Identity.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Identity.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasFilter("revoked_at IS NULL AND used_at IS NULL AND replaced_by_session_id IS NULL");

                    b.HasIndex("FamilyId");

                    b.HasIndex("ReplacedBySessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_sessions", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<DateTimeOffset?>("FailedLoginWindowStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_login_window_started_at");

                    b.Property<string>("LockType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("lock_type");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username_normalized");

                    b.HasKey("Id");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Indexing.IndexScanItem", b =>
                {
                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_id");

                    b.Property<string>("RelativePath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("relative_path");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("entry_type");

                    b.Property<string>("IsolationReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("isolation_reason");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("ParentRelativePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("parent_relative_path");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("SourceFileKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_file_key");

                    b.Property<DateTimeOffset>("SourceModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_modified_at");

                    b.HasKey("ScanId", "RelativePath");

                    b.HasIndex("ScanId", "SourceFileKey")
                        .HasDatabaseName("ix_index_scan_items_scan_source_key")
                        .HasFilter("source_file_key IS NOT NULL");

                    b.HasIndex("ScanId", "OwnerUserId", "ParentRelativePath")
                        .HasDatabaseName("ix_index_scan_items_scan_owner_parent");

                    b.ToTable("index_scan_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_index_scan_items_size", "size >= 0");
                        });
                });

            modelBuilder.Entity("KuraStorage.Domain.Indexing.IndexScanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AddedCount")
                        .HasColumnType("integer")
                        .HasColumnName("added_count");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("EnumeratedCount")
                        .HasColumnType("integer")
                        .HasColumnName("enumerated_count");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<int>("IsolatedCount")
                        .HasColumnType("integer")
                        .HasColumnName("isolated_count");

                    b.Property<int>("MissingCount")
                        .HasColumnType("integer")
                        .HasColumnName("missing_count");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.Property<int>("MovedCount")
                        .HasColumnType("integer")
                        .HasColumnName("moved_count");

                    b.Property<int>("RevivedCount")
                        .HasColumnType("integer")
                        .HasColumnName("revived_count");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer")
                        .HasColumnName("updated_count");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_index_scan_runs_started_at");

                    b.HasIndex("Status", "StartedAt")
                        .HasDatabaseName("ix_index_scan_runs_status_started_at");

                    b.ToTable("index_scan_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_index_scan_runs_completion", "(status = 'RUNNING' AND completed_at IS NULL) OR (status <> 'RUNNING' AND completed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_index_scan_runs_counts", "enumerated_count >= 0 AND added_count >= 0 AND updated_count >= 0 AND moved_count >= 0 AND candidate_count >= 0 AND missing_count >= 0 AND revived_count >= 0 AND isolated_count >= 0 AND error_count >= 0");

                            t.HasCheckConstraint("ck_index_scan_runs_error_code", "(status = 'FAILED' AND error_code IS NOT NULL) OR (status <> 'FAILED' AND error_code IS NULL)");
                        });
                });

            modelBuilder.Entity("KuraStorage.Domain.Maintenance.TrashPurgeRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("DeletedRootCount")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_root_count");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<int>("ExaminedRootCount")
                        .HasColumnType("integer")
                        .HasColumnName("examined_root_count");

                    b.Property<long>("ReleasedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("released_bytes");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_trash_purge_runs_started_at");

                    b.ToTable("trash_purge_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_trash_purge_runs_completion", "(status = 'RUNNING' AND completed_at IS NULL) OR (status <> 'RUNNING' AND completed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_trash_purge_runs_deleted", "deleted_root_count >= 0 AND deleted_root_count <= examined_root_count");

                            t.HasCheckConstraint("ck_trash_purge_runs_errors", "error_count >= 0");

                            t.HasCheckConstraint("ck_trash_purge_runs_examined", "examined_root_count >= 0");

                            t.HasCheckConstraint("ck_trash_purge_runs_released", "released_bytes >= 0");
                        });
                });

            modelBuilder.Entity("KuraStorage.Domain.Media.DerivativeLease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DerivativeId")
                        .HasColumnType("uuid")
                        .HasColumnName("derivative_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("LeaseType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("lease_type");

                    b.Property<Guid>("OwnerToken")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_token");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DerivativeId", "ExpiresAt")
                        .HasDatabaseName("ix_derivative_leases_active");

                    b.HasIndex("ExpiresAt", "Id")
                        .HasDatabaseName("ix_derivative_leases_expiry");

                    b.HasIndex("DerivativeId", "LeaseType", "OwnerToken")
                        .IsUnique()
                        .HasDatabaseName("ux_derivative_leases_owner");

                    b.ToTable("derivative_leases", null, t =>
                        {
                            t.HasCheckConstraint("ck_derivative_leases_type", "lease_type IN ('GENERATION', 'DELIVERY')");
                        });
                });

            modelBuilder.Entity("KuraStorage.Domain.Media.FileDerivative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DerivativeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("derivative_type");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_at");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<int>("ProfileVersion")
                        .HasColumnType("integer")
                        .HasColumnName("profile_version");

                    b.Property<string>("RelativePath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("relative_path");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<Guid>("SourceFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_file_id");

                    b.Property<long>("SourceVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("source_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SourceFileId", "Status")
                        .HasDatabaseName("ix_file_derivatives_source_status");

                    b.HasIndex("Status", "LeaseUntil")
                        .HasDatabaseName("ix_file_derivatives_status_lease");

                    b.HasIndex("DerivativeType", "Status", "LastAccessedAt", "Id")
                        .HasDatabaseName("ix_file_derivatives_type_lru");

                    b.HasIndex("SourceFileId", "SourceVersion", "DerivativeType", "ProfileVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_file_derivatives_logical_key");

                    b.HasIndex("Status", "ExpiresAt", "LastAccessedAt", "Id")
                        .HasDatabaseName("ix_file_derivatives_cleanup");

                    b.ToTable("file_derivatives", null, t =>
                        {
                            t.HasCheckConstraint("ck_file_derivatives_cache_expiry", "derivative_type IN ('THUMBNAIL', 'PDF_THUMBNAIL') OR status <> 'READY' OR (last_accessed_at IS NOT NULL AND expires_at > last_accessed_at)");

                            t.HasCheckConstraint("ck_file_derivatives_failed_error", "status <> 'FAILED' OR error_code IS NOT NULL");

                            t.HasCheckConstraint("ck_file_derivatives_profile_version", "profile_version >= 1");

                            t.HasCheckConstraint("ck_file_derivatives_ready", "(status = 'READY' AND size > 0 AND relative_path IS NOT NULL) OR (status IN ('PENDING', 'RUNNING', 'FAILED') AND size = 0 AND relative_path IS NULL) OR (status IN ('BLOCKED_SOURCE_MISSING', 'DELETING') AND ((size = 0 AND relative_path IS NULL) OR (size > 0 AND relative_path IS NOT NULL)))");

                            t.HasCheckConstraint("ck_file_derivatives_revision", "revision >= 1");

                            t.HasCheckConstraint("ck_file_derivatives_size", "size >= 0");

                            t.HasCheckConstraint("ck_file_derivatives_source_version", "source_version >= 1");

                            t.HasCheckConstraint("ck_file_derivatives_status", "status IN ('PENDING', 'RUNNING', 'READY', 'FAILED', 'BLOCKED_SOURCE_MISSING', 'DELETING')");

                            t.HasCheckConstraint("ck_file_derivatives_thumbnail_expiry", "derivative_type NOT IN ('THUMBNAIL', 'PDF_THUMBNAIL') OR (expires_at IS NULL AND last_accessed_at IS NULL)");
                        });
                });

            modelBuilder.Entity("KuraStorage.Domain.Media.MediaJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DerivativeId")
                        .HasColumnType("uuid")
                        .HasColumnName("derivative_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<DateTimeOffset?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("heartbeat_at");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("job_type");

                    b.Property<long?>("ProcessedDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("processed_duration_ms");

                    b.Property<int?>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<long?>("TotalDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("total_duration_ms");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("WorkerToken")
                        .HasColumnType("uuid")
                        .HasColumnName("worker_token");

                    b.HasKey("Id");

                    b.HasIndex("DerivativeId")
                        .HasDatabaseName("ix_media_jobs_derivative");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("DerivativeId", "Status")
                        .IsUnique()
                        .HasDatabaseName("ux_media_jobs_active_derivative")
                        .HasFilter("status IN ('QUEUED', 'RUNNING')");

                    b.HasIndex("Status", "CompletedAt", "Id")
                        .HasDatabaseName("ix_media_jobs_history_cleanup");

                    b.HasIndex("Status", "HeartbeatAt", "Id")
                        .HasDatabaseName("ix_media_jobs_stale");

                    b.HasIndex("Status", "AvailableAt", "CreatedAt", "Id")
                        .HasDatabaseName("ix_media_jobs_queue");

                    b.ToTable("media_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_media_jobs_attempts", "attempt_count >= 0 AND attempt_count <= 3");

                            t.HasCheckConstraint("ck_media_jobs_completion", "(status IN ('COMPLETED', 'FAILED', 'CANCELLED') AND completed_at IS NOT NULL) OR (status IN ('QUEUED', 'RUNNING') AND completed_at IS NULL)");

                            t.HasCheckConstraint("ck_media_jobs_duration", "(processed_duration_ms IS NULL OR processed_duration_ms >= 0) AND (total_duration_ms IS NULL OR total_duration_ms >= 0) AND (processed_duration_ms IS NULL OR total_duration_ms IS NULL OR processed_duration_ms <= total_duration_ms)");

                            t.HasCheckConstraint("ck_media_jobs_error", "status NOT IN ('FAILED', 'CANCELLED') OR error_code IS NOT NULL");

                            t.HasCheckConstraint("ck_media_jobs_owner", "(status = 'RUNNING' AND worker_token IS NOT NULL AND heartbeat_at IS NOT NULL) OR (status <> 'RUNNING' AND worker_token IS NULL AND heartbeat_at IS NULL)");

                            t.HasCheckConstraint("ck_media_jobs_progress", "progress_percent IS NULL OR (progress_percent >= 0 AND progress_percent <= 100)");

                            t.HasCheckConstraint("ck_media_jobs_status", "status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("KuraStorage.Domain.Organization.EntryTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<DateTimeOffset>("AttachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attached_at");

                    b.HasKey("TagId", "EntryId");

                    b.HasIndex("EntryId", "TagId")
                        .HasDatabaseName("ix_entry_tags_entry_id_tag_id");

                    b.ToTable("entry_tags", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Organization.FavoriteEntry", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<DateTimeOffset>("FavoritedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("favorited_at");

                    b.HasKey("UserId", "EntryId");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("ix_favorite_entries_entry_id");

                    b.HasIndex("UserId", "FavoritedAt", "EntryId")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_favorite_entries_user_favorited_at_entry_id");

                    b.ToTable("favorite_entries", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Organization.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "NameKey")
                        .IsUnique()
                        .HasDatabaseName("ux_tags_user_name_key");

                    b.HasIndex("UserId", "NameKey", "Id")
                        .HasDatabaseName("ix_tags_user_name_key_id");

                    b.ToTable("tags", null, t =>
                        {
                            t.HasCheckConstraint("ck_tags_name", "char_length(name) BETWEEN 1 AND 50 AND name = btrim(name)");
                        });
                });

            modelBuilder.Entity("KuraStorage.Domain.Sharing.Share", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid>("TargetEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_entry_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TargetEntryId")
                        .IsUnique()
                        .HasDatabaseName("ux_shares_target_entry_id");

                    b.HasIndex("OwnerUserId", "UpdatedAt", "Id")
                        .HasDatabaseName("ix_shares_owner_updated_id");

                    b.ToTable("shares", (string)null);
                });

            modelBuilder.Entity("KuraStorage.Domain.Sharing.ShareMember", b =>
                {
                    b.Property<Guid>("ShareId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("permission");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ShareId", "UserId");

                    b.HasIndex("UserId", "ShareId")
                        .HasDatabaseName("ix_share_members_user_share");

                    b.ToTable("share_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_share_members_permission", "\"permission\" IN ('VIEWER', 'CONTRIBUTOR', 'EDITOR', 'MANAGER')");
                        });
                });

            modelBuilder.Entity("KuraStorage.Domain.Transfers.UploadSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset?>("CleanedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cleaned_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DestinationFolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_folder_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ExpectedSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("expected_sha256");

                    b.Property<long>("ExpectedSize")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_size");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FileEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_entry_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid?>("FileOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_operation_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<long?>("LastChunkLength")
                        .HasColumnType("bigint")
                        .HasColumnName("last_chunk_length");

                    b.Property<long?>("LastChunkOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("last_chunk_offset");

                    b.Property<string>("LastChunkSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_chunk_sha256");

                    b.Property<long>("ReceivedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("received_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetOwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_owner_user_id");

                    b.Property<string>("TemporaryRelativePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("temporary_relative_path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DestinationFolderId");

                    b.HasIndex("FileOperationId")
                        .IsUnique()
                        .HasDatabaseName("ux_upload_sessions_file_operation_id")
                        .HasFilter("\"file_operation_id\" IS NOT NULL");

                    b.HasIndex("TargetOwnerUserId");

                    b.HasIndex("ActorUserId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_upload_sessions_actor_idempotency_key");

                    b.HasIndex("ActorUserId", "Status")
                        .HasDatabaseName("ix_upload_sessions_actor_status");

                    b.HasIndex("DeviceId", "Status", "Id")
                        .HasDatabaseName("ix_upload_sessions_device_status");

                    b.HasIndex("Status", "ExpiresAt", "Id")
                        .HasDatabaseName("ix_upload_sessions_cleanup_candidates");

                    b.ToTable("upload_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_upload_sessions_byte_range", "\"expected_size\" >= 0 AND \"received_bytes\" >= 0 AND \"received_bytes\" <= \"expected_size\"");

                            t.HasCheckConstraint("ck_upload_sessions_expiration", "\"expires_at\" <= \"absolute_expires_at\"");
                        });
                });

            modelBuilder.Entity("KuraStorage.Domain.Files.FileEntry", b =>
                {
                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KuraStorage.Domain.Files.FileEntry", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KuraStorage.Domain.Files.FileOperation", b =>
                {
                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Files.RecentFile", b =>
                {
                    b.HasOne("KuraStorage.Domain.Files.FileEntry", null)
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Identity.Device", b =>
                {
                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Identity.RefreshSession", b =>
                {
                    b.HasOne("KuraStorage.Domain.Identity.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuraStorage.Domain.Identity.RefreshSession", null)
                        .WithMany()
                        .HasForeignKey("ReplacedBySessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Indexing.IndexScanItem", b =>
                {
                    b.HasOne("KuraStorage.Domain.Indexing.IndexScanRun", null)
                        .WithMany()
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Media.DerivativeLease", b =>
                {
                    b.HasOne("KuraStorage.Domain.Media.FileDerivative", null)
                        .WithMany()
                        .HasForeignKey("DerivativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Media.FileDerivative", b =>
                {
                    b.HasOne("KuraStorage.Domain.Files.FileEntry", null)
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Media.MediaJob", b =>
                {
                    b.HasOne("KuraStorage.Domain.Media.FileDerivative", null)
                        .WithMany()
                        .HasForeignKey("DerivativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Organization.EntryTag", b =>
                {
                    b.HasOne("KuraStorage.Domain.Files.FileEntry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuraStorage.Domain.Organization.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Organization.FavoriteEntry", b =>
                {
                    b.HasOne("KuraStorage.Domain.Files.FileEntry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Organization.Tag", b =>
                {
                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Sharing.Share", b =>
                {
                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KuraStorage.Domain.Files.FileEntry", null)
                        .WithOne()
                        .HasForeignKey("KuraStorage.Domain.Sharing.Share", "TargetEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Sharing.ShareMember", b =>
                {
                    b.HasOne("KuraStorage.Domain.Sharing.Share", null)
                        .WithMany("Members")
                        .HasForeignKey("ShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Transfers.UploadSession", b =>
                {
                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KuraStorage.Domain.Files.FileEntry", null)
                        .WithMany()
                        .HasForeignKey("DestinationFolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KuraStorage.Domain.Identity.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KuraStorage.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("TargetOwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KuraStorage.Domain.Sharing.Share", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
